linters-settings:
  goimports:
    local-prefixes: github.com/metis-labs/metis-server

linters:
  enable:
    - bodyclose
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - golint
    - goprintffuncname
    - gosec
    - interfacer
    - lll
    - misspell
    - nakedret

issues:
  exclude-use-default: false
